image: d.cydev.ru/media:latest
env:
  - GOPATH=/var/cache/drone
script:
  - go get github.com/smartystreets/goconvey/convey
  - go get -v .
  - sudo start mongodb
  - sleep 10
  - go test
services:
  - mongodb
  - redis
  - d.cydev.ru/weed:server
