FROM cydev.ru:5000/media

ENV ROOT /go/src/github.com/ernado/poputchiki
RUN mkdir -p /go/src/github.com/ernado/poputchiki
RUN git clone github.com:ernado/poputchiki.git github.com/ernado/poputchiki
RUN cd $ROOT && version=VERSION git pull
RUN cd $ROOT && go get .

ENTRYPOINT ["/go/bin/poputchiki"]
